// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: peripheral.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NewPeripheral_PeripheralType int32

const (
	NewPeripheral_THERMAL  NewPeripheral_PeripheralType = 0
	NewPeripheral_PARTICLE NewPeripheral_PeripheralType = 1
)

// Enum value maps for NewPeripheral_PeripheralType.
var (
	NewPeripheral_PeripheralType_name = map[int32]string{
		0: "THERMAL",
		1: "PARTICLE",
	}
	NewPeripheral_PeripheralType_value = map[string]int32{
		"THERMAL":  0,
		"PARTICLE": 1,
	}
)

func (x NewPeripheral_PeripheralType) Enum() *NewPeripheral_PeripheralType {
	p := new(NewPeripheral_PeripheralType)
	*p = x
	return p
}

func (x NewPeripheral_PeripheralType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NewPeripheral_PeripheralType) Descriptor() protoreflect.EnumDescriptor {
	return file_peripheral_proto_enumTypes[0].Descriptor()
}

func (NewPeripheral_PeripheralType) Type() protoreflect.EnumType {
	return &file_peripheral_proto_enumTypes[0]
}

func (x NewPeripheral_PeripheralType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NewPeripheral_PeripheralType.Descriptor instead.
func (NewPeripheral_PeripheralType) EnumDescriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{0, 0}
}

type Peripheral_PeripheralType int32

const (
	Peripheral_THERMAL  Peripheral_PeripheralType = 0
	Peripheral_PARTICLE Peripheral_PeripheralType = 1
)

// Enum value maps for Peripheral_PeripheralType.
var (
	Peripheral_PeripheralType_name = map[int32]string{
		0: "THERMAL",
		1: "PARTICLE",
	}
	Peripheral_PeripheralType_value = map[string]int32{
		"THERMAL":  0,
		"PARTICLE": 1,
	}
)

func (x Peripheral_PeripheralType) Enum() *Peripheral_PeripheralType {
	p := new(Peripheral_PeripheralType)
	*p = x
	return p
}

func (x Peripheral_PeripheralType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Peripheral_PeripheralType) Descriptor() protoreflect.EnumDescriptor {
	return file_peripheral_proto_enumTypes[1].Descriptor()
}

func (Peripheral_PeripheralType) Type() protoreflect.EnumType {
	return &file_peripheral_proto_enumTypes[1]
}

func (x Peripheral_PeripheralType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Peripheral_PeripheralType.Descriptor instead.
func (Peripheral_PeripheralType) EnumDescriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{1, 0}
}

type NewPeripheral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerUserId  string                       `protobuf:"bytes,1,opt,name=ownerUserId,proto3" json:"ownerUserId,omitempty"`
	DeploymentId string                       `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	HardwareId   *NullableString              `protobuf:"bytes,3,opt,name=hardwareId,proto3" json:"hardwareId,omitempty"`
	Type         NewPeripheral_PeripheralType `protobuf:"varint,4,opt,name=type,proto3,enum=api.NewPeripheral_PeripheralType" json:"type,omitempty"`
	Name         string                       `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Unit         string                       `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *NewPeripheral) Reset() {
	*x = NewPeripheral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peripheral_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPeripheral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPeripheral) ProtoMessage() {}

func (x *NewPeripheral) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPeripheral.ProtoReflect.Descriptor instead.
func (*NewPeripheral) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{0}
}

func (x *NewPeripheral) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *NewPeripheral) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *NewPeripheral) GetHardwareId() *NullableString {
	if x != nil {
		return x.HardwareId
	}
	return nil
}

func (x *NewPeripheral) GetType() NewPeripheral_PeripheralType {
	if x != nil {
		return x.Type
	}
	return NewPeripheral_THERMAL
}

func (x *NewPeripheral) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewPeripheral) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type Peripheral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerUserId  string                    `protobuf:"bytes,1,opt,name=ownerUserId,proto3" json:"ownerUserId,omitempty"`
	DeploymentId string                    `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	Id           string                    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	HardwareId   *NullableString           `protobuf:"bytes,4,opt,name=hardwareId,proto3" json:"hardwareId,omitempty"`
	Type         Peripheral_PeripheralType `protobuf:"varint,5,opt,name=type,proto3,enum=api.Peripheral_PeripheralType" json:"type,omitempty"`
	Name         string                    `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Unit         string                    `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *Peripheral) Reset() {
	*x = Peripheral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peripheral_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peripheral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peripheral) ProtoMessage() {}

func (x *Peripheral) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peripheral.ProtoReflect.Descriptor instead.
func (*Peripheral) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{1}
}

func (x *Peripheral) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Peripheral) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *Peripheral) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peripheral) GetHardwareId() *NullableString {
	if x != nil {
		return x.HardwareId
	}
	return nil
}

func (x *Peripheral) GetType() Peripheral_PeripheralType {
	if x != nil {
		return x.Type
	}
	return Peripheral_THERMAL
}

func (x *Peripheral) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peripheral) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type GetDeploymentPeripheralsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeploymentId string `protobuf:"bytes,1,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
}

func (x *GetDeploymentPeripheralsRequest) Reset() {
	*x = GetDeploymentPeripheralsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peripheral_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeploymentPeripheralsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentPeripheralsRequest) ProtoMessage() {}

func (x *GetDeploymentPeripheralsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentPeripheralsRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentPeripheralsRequest) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeploymentPeripheralsRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type GetPeripheralRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeripheralId string `protobuf:"bytes,1,opt,name=peripheralId,proto3" json:"peripheralId,omitempty"`
}

func (x *GetPeripheralRequest) Reset() {
	*x = GetPeripheralRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peripheral_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeripheralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeripheralRequest) ProtoMessage() {}

func (x *GetPeripheralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeripheralRequest.ProtoReflect.Descriptor instead.
func (*GetPeripheralRequest) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeripheralRequest) GetPeripheralId() string {
	if x != nil {
		return x.PeripheralId
	}
	return ""
}

type LinkHardwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HardwareId   string `protobuf:"bytes,1,opt,name=hardwareId,proto3" json:"hardwareId,omitempty"`
	PeripheralId string `protobuf:"bytes,2,opt,name=peripheralId,proto3" json:"peripheralId,omitempty"`
}

func (x *LinkHardwareRequest) Reset() {
	*x = LinkHardwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peripheral_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkHardwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkHardwareRequest) ProtoMessage() {}

func (x *LinkHardwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkHardwareRequest.ProtoReflect.Descriptor instead.
func (*LinkHardwareRequest) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{4}
}

func (x *LinkHardwareRequest) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *LinkHardwareRequest) GetPeripheralId() string {
	if x != nil {
		return x.PeripheralId
	}
	return ""
}

type NullableString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//	*NullableString_Null
	//	*NullableString_Data
	Kind isNullableString_Kind `protobuf_oneof:"kind"`
}

func (x *NullableString) Reset() {
	*x = NullableString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peripheral_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableString) ProtoMessage() {}

func (x *NullableString) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableString.ProtoReflect.Descriptor instead.
func (*NullableString) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{5}
}

func (m *NullableString) GetKind() isNullableString_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *NullableString) GetNull() _struct.NullValue {
	if x, ok := x.GetKind().(*NullableString_Null); ok {
		return x.Null
	}
	return _struct.NullValue_NULL_VALUE
}

func (x *NullableString) GetData() string {
	if x, ok := x.GetKind().(*NullableString_Data); ok {
		return x.Data
	}
	return ""
}

type isNullableString_Kind interface {
	isNullableString_Kind()
}

type NullableString_Null struct {
	Null _struct.NullValue `protobuf:"varint,1,opt,name=null,proto3,enum=google.protobuf.NullValue,oneof"`
}

type NullableString_Data struct {
	Data string `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*NullableString_Null) isNullableString_Kind() {}

func (*NullableString_Data) isNullableString_Kind() {}

var File_peripheral_proto protoreflect.FileDescriptor

var file_peripheral_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x0b, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x96, 0x02, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x0a, 0x68, 0x61,
	0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x0a, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x12,
	0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61,
	0x6c, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x2b,
	0x0a, 0x0e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x54, 0x48, 0x45, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x50, 0x41, 0x52, 0x54, 0x49, 0x43, 0x4c, 0x45, 0x10, 0x01, 0x22, 0xa0, 0x02, 0x0a, 0x0a,
	0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x33, 0x0a, 0x0a, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x68, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x61, 0x6c, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69,
	0x74, 0x22, 0x2b, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x48, 0x45, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x50, 0x41, 0x52, 0x54, 0x49, 0x43, 0x4c, 0x45, 0x10, 0x01, 0x22, 0x45,
	0x0a, 0x1f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x50,
	0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x49,
	0x64, 0x22, 0x59, 0x0a, 0x13, 0x4c, 0x69, 0x6e, 0x6b, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61, 0x72, 0x64,
	0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x61,
	0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x65, 0x72, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x0e,
	0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x30,
	0x0a, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4e,
	0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x75, 0x6c, 0x6c,
	0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x32, 0xd4,
	0x02, 0x0a, 0x1b, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12,
	0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x37, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12,
	0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x61, 0x6c, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x61, 0x6c, 0x12, 0x2f, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65,
	0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x1a, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x0c, 0x4c, 0x69, 0x6e, 0x6b, 0x48, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x6e, 0x6b,
	0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c,
	0x12, 0x53, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x12, 0x24, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x61, 0x6c, 0x30, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_peripheral_proto_rawDescOnce sync.Once
	file_peripheral_proto_rawDescData = file_peripheral_proto_rawDesc
)

func file_peripheral_proto_rawDescGZIP() []byte {
	file_peripheral_proto_rawDescOnce.Do(func() {
		file_peripheral_proto_rawDescData = protoimpl.X.CompressGZIP(file_peripheral_proto_rawDescData)
	})
	return file_peripheral_proto_rawDescData
}

var file_peripheral_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_peripheral_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_peripheral_proto_goTypes = []interface{}{
	(NewPeripheral_PeripheralType)(0),       // 0: api.NewPeripheral.PeripheralType
	(Peripheral_PeripheralType)(0),          // 1: api.Peripheral.PeripheralType
	(*NewPeripheral)(nil),                   // 2: api.NewPeripheral
	(*Peripheral)(nil),                      // 3: api.Peripheral
	(*GetDeploymentPeripheralsRequest)(nil), // 4: api.GetDeploymentPeripheralsRequest
	(*GetPeripheralRequest)(nil),            // 5: api.GetPeripheralRequest
	(*LinkHardwareRequest)(nil),             // 6: api.LinkHardwareRequest
	(*NullableString)(nil),                  // 7: api.NullableString
	(_struct.NullValue)(0),                  // 8: google.protobuf.NullValue
	(*Empty)(nil),                           // 9: api.Empty
}
var file_peripheral_proto_depIdxs = []int32{
	7,  // 0: api.NewPeripheral.hardwareId:type_name -> api.NullableString
	0,  // 1: api.NewPeripheral.type:type_name -> api.NewPeripheral.PeripheralType
	7,  // 2: api.Peripheral.hardwareId:type_name -> api.NullableString
	1,  // 3: api.Peripheral.type:type_name -> api.Peripheral.PeripheralType
	8,  // 4: api.NullableString.null:type_name -> google.protobuf.NullValue
	5,  // 5: api.PeripheralManagementService.GetPeripheral:input_type -> api.GetPeripheralRequest
	2,  // 6: api.PeripheralManagementService.CreatePeripheral:input_type -> api.NewPeripheral
	3,  // 7: api.PeripheralManagementService.RemovePeripheral:input_type -> api.Peripheral
	6,  // 8: api.PeripheralManagementService.LinkHardware:input_type -> api.LinkHardwareRequest
	4,  // 9: api.PeripheralManagementService.GetDeploymentPeripherals:input_type -> api.GetDeploymentPeripheralsRequest
	3,  // 10: api.PeripheralManagementService.GetPeripheral:output_type -> api.Peripheral
	3,  // 11: api.PeripheralManagementService.CreatePeripheral:output_type -> api.Peripheral
	9,  // 12: api.PeripheralManagementService.RemovePeripheral:output_type -> api.Empty
	3,  // 13: api.PeripheralManagementService.LinkHardware:output_type -> api.Peripheral
	3,  // 14: api.PeripheralManagementService.GetDeploymentPeripherals:output_type -> api.Peripheral
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_peripheral_proto_init() }
func file_peripheral_proto_init() {
	if File_peripheral_proto != nil {
		return
	}
	file_empty_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_peripheral_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPeripheral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peripheral_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peripheral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peripheral_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeploymentPeripheralsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peripheral_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeripheralRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peripheral_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkHardwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peripheral_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_peripheral_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*NullableString_Null)(nil),
		(*NullableString_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peripheral_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peripheral_proto_goTypes,
		DependencyIndexes: file_peripheral_proto_depIdxs,
		EnumInfos:         file_peripheral_proto_enumTypes,
		MessageInfos:      file_peripheral_proto_msgTypes,
	}.Build()
	File_peripheral_proto = out.File
	file_peripheral_proto_rawDesc = nil
	file_peripheral_proto_goTypes = nil
	file_peripheral_proto_depIdxs = nil
}
