// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: peripheral.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NewPeripheral_PeripheralType int32

const (
	NewPeripheral_THERMAL  NewPeripheral_PeripheralType = 0
	NewPeripheral_PARTICLE NewPeripheral_PeripheralType = 1
)

// Enum value maps for NewPeripheral_PeripheralType.
var (
	NewPeripheral_PeripheralType_name = map[int32]string{
		0: "THERMAL",
		1: "PARTICLE",
	}
	NewPeripheral_PeripheralType_value = map[string]int32{
		"THERMAL":  0,
		"PARTICLE": 1,
	}
)

func (x NewPeripheral_PeripheralType) Enum() *NewPeripheral_PeripheralType {
	p := new(NewPeripheral_PeripheralType)
	*p = x
	return p
}

func (x NewPeripheral_PeripheralType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NewPeripheral_PeripheralType) Descriptor() protoreflect.EnumDescriptor {
	return file_peripheral_proto_enumTypes[0].Descriptor()
}

func (NewPeripheral_PeripheralType) Type() protoreflect.EnumType {
	return &file_peripheral_proto_enumTypes[0]
}

func (x NewPeripheral_PeripheralType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NewPeripheral_PeripheralType.Descriptor instead.
func (NewPeripheral_PeripheralType) EnumDescriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{0, 0}
}

type Peripheral_PeripheralType int32

const (
	Peripheral_THERMAL  Peripheral_PeripheralType = 0
	Peripheral_PARTICLE Peripheral_PeripheralType = 1
)

// Enum value maps for Peripheral_PeripheralType.
var (
	Peripheral_PeripheralType_name = map[int32]string{
		0: "THERMAL",
		1: "PARTICLE",
	}
	Peripheral_PeripheralType_value = map[string]int32{
		"THERMAL":  0,
		"PARTICLE": 1,
	}
)

func (x Peripheral_PeripheralType) Enum() *Peripheral_PeripheralType {
	p := new(Peripheral_PeripheralType)
	*p = x
	return p
}

func (x Peripheral_PeripheralType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Peripheral_PeripheralType) Descriptor() protoreflect.EnumDescriptor {
	return file_peripheral_proto_enumTypes[1].Descriptor()
}

func (Peripheral_PeripheralType) Type() protoreflect.EnumType {
	return &file_peripheral_proto_enumTypes[1]
}

func (x Peripheral_PeripheralType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Peripheral_PeripheralType.Descriptor instead.
func (Peripheral_PeripheralType) EnumDescriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{1, 0}
}

type NewPeripheral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerUserId  string                       `protobuf:"bytes,1,opt,name=ownerUserId,proto3" json:"ownerUserId,omitempty"`
	DeploymentId string                       `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	HardwareId   string                       `protobuf:"bytes,3,opt,name=hardwareId,proto3" json:"hardwareId,omitempty"`
	Type         NewPeripheral_PeripheralType `protobuf:"varint,4,opt,name=type,proto3,enum=api.NewPeripheral_PeripheralType" json:"type,omitempty"`
}

func (x *NewPeripheral) Reset() {
	*x = NewPeripheral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peripheral_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPeripheral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPeripheral) ProtoMessage() {}

func (x *NewPeripheral) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPeripheral.ProtoReflect.Descriptor instead.
func (*NewPeripheral) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{0}
}

func (x *NewPeripheral) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *NewPeripheral) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *NewPeripheral) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *NewPeripheral) GetType() NewPeripheral_PeripheralType {
	if x != nil {
		return x.Type
	}
	return NewPeripheral_THERMAL
}

type Peripheral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerUserId  string                    `protobuf:"bytes,1,opt,name=ownerUserId,proto3" json:"ownerUserId,omitempty"`
	DeploymentId string                    `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	Id           string                    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	HardwareId   string                    `protobuf:"bytes,4,opt,name=hardwareId,proto3" json:"hardwareId,omitempty"`
	Type         Peripheral_PeripheralType `protobuf:"varint,5,opt,name=type,proto3,enum=api.Peripheral_PeripheralType" json:"type,omitempty"`
}

func (x *Peripheral) Reset() {
	*x = Peripheral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peripheral_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peripheral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peripheral) ProtoMessage() {}

func (x *Peripheral) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peripheral.ProtoReflect.Descriptor instead.
func (*Peripheral) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{1}
}

func (x *Peripheral) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Peripheral) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *Peripheral) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peripheral) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *Peripheral) GetType() Peripheral_PeripheralType {
	if x != nil {
		return x.Type
	}
	return Peripheral_THERMAL
}

var File_peripheral_proto protoreflect.FileDescriptor

var file_peripheral_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x0b, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x01, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x50, 0x65, 0x72, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4e, 0x65, 0x77, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x50,
	0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x48, 0x45, 0x52, 0x4d, 0x41, 0x4c,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x41, 0x52, 0x54, 0x49, 0x43, 0x4c, 0x45, 0x10, 0x01,
	0x22, 0xe3, 0x01, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12,
	0x20, 0x0a, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72,
	0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x61, 0x6c, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x0e, 0x50, 0x65, 0x72,
	0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x54,
	0x48, 0x45, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x41, 0x52, 0x54,
	0x49, 0x43, 0x4c, 0x45, 0x10, 0x01, 0x32, 0x87, 0x01, 0x0a, 0x1b, 0x50, 0x65, 0x72, 0x69, 0x70,
	0x68, 0x65, 0x72, 0x61, 0x6c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4e, 0x65, 0x77, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x1a, 0x0f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12,
	0x2f, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x61, 0x6c, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x61, 0x6c, 0x1a, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x42, 0x0e, 0x5a, 0x0c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_peripheral_proto_rawDescOnce sync.Once
	file_peripheral_proto_rawDescData = file_peripheral_proto_rawDesc
)

func file_peripheral_proto_rawDescGZIP() []byte {
	file_peripheral_proto_rawDescOnce.Do(func() {
		file_peripheral_proto_rawDescData = protoimpl.X.CompressGZIP(file_peripheral_proto_rawDescData)
	})
	return file_peripheral_proto_rawDescData
}

var file_peripheral_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_peripheral_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_peripheral_proto_goTypes = []interface{}{
	(NewPeripheral_PeripheralType)(0), // 0: api.NewPeripheral.PeripheralType
	(Peripheral_PeripheralType)(0),    // 1: api.Peripheral.PeripheralType
	(*NewPeripheral)(nil),             // 2: api.NewPeripheral
	(*Peripheral)(nil),                // 3: api.Peripheral
	(*Empty)(nil),                     // 4: api.Empty
}
var file_peripheral_proto_depIdxs = []int32{
	0, // 0: api.NewPeripheral.type:type_name -> api.NewPeripheral.PeripheralType
	1, // 1: api.Peripheral.type:type_name -> api.Peripheral.PeripheralType
	2, // 2: api.PeripheralManagementService.CreatePeripheral:input_type -> api.NewPeripheral
	3, // 3: api.PeripheralManagementService.RemovePeripheral:input_type -> api.Peripheral
	3, // 4: api.PeripheralManagementService.CreatePeripheral:output_type -> api.Peripheral
	4, // 5: api.PeripheralManagementService.RemovePeripheral:output_type -> api.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_peripheral_proto_init() }
func file_peripheral_proto_init() {
	if File_peripheral_proto != nil {
		return
	}
	file_empty_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_peripheral_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPeripheral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peripheral_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peripheral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peripheral_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peripheral_proto_goTypes,
		DependencyIndexes: file_peripheral_proto_depIdxs,
		EnumInfos:         file_peripheral_proto_enumTypes,
		MessageInfos:      file_peripheral_proto_msgTypes,
	}.Build()
	File_peripheral_proto = out.File
	file_peripheral_proto_rawDesc = nil
	file_peripheral_proto_goTypes = nil
	file_peripheral_proto_depIdxs = nil
}
