// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PeripheralManagementServiceClient is the client API for PeripheralManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeripheralManagementServiceClient interface {
	CreatePeripheral(ctx context.Context, in *Peripheral, opts ...grpc.CallOption) (*Peripheral, error)
	RemovePeripheral(ctx context.Context, in *Peripheral, opts ...grpc.CallOption) (*Empty, error)
}

type peripheralManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeripheralManagementServiceClient(cc grpc.ClientConnInterface) PeripheralManagementServiceClient {
	return &peripheralManagementServiceClient{cc}
}

func (c *peripheralManagementServiceClient) CreatePeripheral(ctx context.Context, in *Peripheral, opts ...grpc.CallOption) (*Peripheral, error) {
	out := new(Peripheral)
	err := c.cc.Invoke(ctx, "/api.PeripheralManagementService/CreatePeripheral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peripheralManagementServiceClient) RemovePeripheral(ctx context.Context, in *Peripheral, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.PeripheralManagementService/RemovePeripheral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeripheralManagementServiceServer is the server API for PeripheralManagementService service.
// All implementations must embed UnimplementedPeripheralManagementServiceServer
// for forward compatibility
type PeripheralManagementServiceServer interface {
	CreatePeripheral(context.Context, *Peripheral) (*Peripheral, error)
	RemovePeripheral(context.Context, *Peripheral) (*Empty, error)
	mustEmbedUnimplementedPeripheralManagementServiceServer()
}

// UnimplementedPeripheralManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPeripheralManagementServiceServer struct {
}

func (UnimplementedPeripheralManagementServiceServer) CreatePeripheral(context.Context, *Peripheral) (*Peripheral, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePeripheral not implemented")
}
func (UnimplementedPeripheralManagementServiceServer) RemovePeripheral(context.Context, *Peripheral) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePeripheral not implemented")
}
func (UnimplementedPeripheralManagementServiceServer) mustEmbedUnimplementedPeripheralManagementServiceServer() {
}

// UnsafePeripheralManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeripheralManagementServiceServer will
// result in compilation errors.
type UnsafePeripheralManagementServiceServer interface {
	mustEmbedUnimplementedPeripheralManagementServiceServer()
}

func RegisterPeripheralManagementServiceServer(s *grpc.Server, srv PeripheralManagementServiceServer) {
	s.RegisterService(&_PeripheralManagementService_serviceDesc, srv)
}

func _PeripheralManagementService_CreatePeripheral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peripheral)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeripheralManagementServiceServer).CreatePeripheral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PeripheralManagementService/CreatePeripheral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeripheralManagementServiceServer).CreatePeripheral(ctx, req.(*Peripheral))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeripheralManagementService_RemovePeripheral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peripheral)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeripheralManagementServiceServer).RemovePeripheral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PeripheralManagementService/RemovePeripheral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeripheralManagementServiceServer).RemovePeripheral(ctx, req.(*Peripheral))
	}
	return interceptor(ctx, in, info, handler)
}

var _PeripheralManagementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PeripheralManagementService",
	HandlerType: (*PeripheralManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePeripheral",
			Handler:    _PeripheralManagementService_CreatePeripheral_Handler,
		},
		{
			MethodName: "RemovePeripheral",
			Handler:    _PeripheralManagementService_RemovePeripheral_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peripheral.proto",
}
