// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deployment.proto

package api;

public final class DeploymentOuterClass {
  private DeploymentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DeploymentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.Deployment)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string ownerUserId = 2;</code>
     * @return The ownerUserId.
     */
    java.lang.String getOwnerUserId();
    /**
     * <code>string ownerUserId = 2;</code>
     * @return The bytes for ownerUserId.
     */
    com.google.protobuf.ByteString
        getOwnerUserIdBytes();

    /**
     * <code>string domain = 3;</code>
     * @return The domain.
     */
    java.lang.String getDomain();
    /**
     * <code>string domain = 3;</code>
     * @return The bytes for domain.
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <code>.api.Deployment.Status status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.api.Deployment.Status status = 4;</code>
     * @return The status.
     */
    api.DeploymentOuterClass.Deployment.Status getStatus();
  }
  /**
   * Protobuf type {@code api.Deployment}
   */
  public  static final class Deployment extends
      com.google.protobuf.GeneratedMessageLite<
          Deployment, Deployment.Builder> implements
      // @@protoc_insertion_point(message_implements:api.Deployment)
      DeploymentOrBuilder {
    private Deployment() {
      id_ = "";
      ownerUserId_ = "";
      domain_ = "";
    }
    /**
     * Protobuf enum {@code api.Deployment.Status}
     */
    public enum Status
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>STARTING_UP = 0;</code>
       */
      STARTING_UP(0),
      /**
       * <code>FAILED = 1;</code>
       */
      FAILED(1),
      /**
       * <code>RUNNING = 2;</code>
       */
      RUNNING(2),
      /**
       * <code>SHUTTING_DOWN = 3;</code>
       */
      SHUTTING_DOWN(3),
      /**
       * <code>UNREACHABLE = 4;</code>
       */
      UNREACHABLE(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>STARTING_UP = 0;</code>
       */
      public static final int STARTING_UP_VALUE = 0;
      /**
       * <code>FAILED = 1;</code>
       */
      public static final int FAILED_VALUE = 1;
      /**
       * <code>RUNNING = 2;</code>
       */
      public static final int RUNNING_VALUE = 2;
      /**
       * <code>SHUTTING_DOWN = 3;</code>
       */
      public static final int SHUTTING_DOWN_VALUE = 3;
      /**
       * <code>UNREACHABLE = 4;</code>
       */
      public static final int UNREACHABLE_VALUE = 4;


      @java.lang.Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return STARTING_UP;
          case 1: return FAILED;
          case 2: return RUNNING;
          case 3: return SHUTTING_DOWN;
          case 4: return UNREACHABLE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              @java.lang.Override
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return StatusVerifier.INSTANCE;
      }

      private static final class StatusVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new StatusVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return Status.forNumber(number) != null;
              }
            };

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:api.Deployment.Status)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.String id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     */
    private void setId(
        java.lang.String value) {
      value.getClass();
  
      id_ = value;
    }
    /**
     * <code>string id = 1;</code>
     */
    private void clearId() {
      
      id_ = getDefaultInstance().getId();
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      id_ = value.toStringUtf8();
      
    }

    public static final int OWNERUSERID_FIELD_NUMBER = 2;
    private java.lang.String ownerUserId_;
    /**
     * <code>string ownerUserId = 2;</code>
     * @return The ownerUserId.
     */
    @java.lang.Override
    public java.lang.String getOwnerUserId() {
      return ownerUserId_;
    }
    /**
     * <code>string ownerUserId = 2;</code>
     * @return The bytes for ownerUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ownerUserId_);
    }
    /**
     * <code>string ownerUserId = 2;</code>
     * @param value The ownerUserId to set.
     */
    private void setOwnerUserId(
        java.lang.String value) {
      value.getClass();
  
      ownerUserId_ = value;
    }
    /**
     * <code>string ownerUserId = 2;</code>
     */
    private void clearOwnerUserId() {
      
      ownerUserId_ = getDefaultInstance().getOwnerUserId();
    }
    /**
     * <code>string ownerUserId = 2;</code>
     * @param value The bytes for ownerUserId to set.
     */
    private void setOwnerUserIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ownerUserId_ = value.toStringUtf8();
      
    }

    public static final int DOMAIN_FIELD_NUMBER = 3;
    private java.lang.String domain_;
    /**
     * <code>string domain = 3;</code>
     * @return The domain.
     */
    @java.lang.Override
    public java.lang.String getDomain() {
      return domain_;
    }
    /**
     * <code>string domain = 3;</code>
     * @return The bytes for domain.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDomainBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(domain_);
    }
    /**
     * <code>string domain = 3;</code>
     * @param value The domain to set.
     */
    private void setDomain(
        java.lang.String value) {
      value.getClass();
  
      domain_ = value;
    }
    /**
     * <code>string domain = 3;</code>
     */
    private void clearDomain() {
      
      domain_ = getDefaultInstance().getDomain();
    }
    /**
     * <code>string domain = 3;</code>
     * @param value The bytes for domain to set.
     */
    private void setDomainBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      domain_ = value.toStringUtf8();
      
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>.api.Deployment.Status status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.api.Deployment.Status status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public api.DeploymentOuterClass.Deployment.Status getStatus() {
      api.DeploymentOuterClass.Deployment.Status result = api.DeploymentOuterClass.Deployment.Status.forNumber(status_);
      return result == null ? api.DeploymentOuterClass.Deployment.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.api.Deployment.Status status = 4;</code>
     * @param value The enum numeric value on the wire for status to set.
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.api.Deployment.Status status = 4;</code>
     * @param value The status to set.
     */
    private void setStatus(api.DeploymentOuterClass.Deployment.Status value) {
      status_ = value.getNumber();
      
    }
    /**
     * <code>.api.Deployment.Status status = 4;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static api.DeploymentOuterClass.Deployment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.Deployment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.Deployment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.Deployment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.Deployment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.Deployment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.Deployment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.Deployment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.DeploymentOuterClass.Deployment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.Deployment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.DeploymentOuterClass.Deployment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.Deployment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.DeploymentOuterClass.Deployment prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.Deployment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.DeploymentOuterClass.Deployment, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.Deployment)
        api.DeploymentOuterClass.DeploymentOrBuilder {
      // Construct using api.DeploymentOuterClass.Deployment.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <code>string ownerUserId = 2;</code>
       * @return The ownerUserId.
       */
      @java.lang.Override
      public java.lang.String getOwnerUserId() {
        return instance.getOwnerUserId();
      }
      /**
       * <code>string ownerUserId = 2;</code>
       * @return The bytes for ownerUserId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOwnerUserIdBytes() {
        return instance.getOwnerUserIdBytes();
      }
      /**
       * <code>string ownerUserId = 2;</code>
       * @param value The ownerUserId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setOwnerUserId(value);
        return this;
      }
      /**
       * <code>string ownerUserId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerUserId() {
        copyOnWrite();
        instance.clearOwnerUserId();
        return this;
      }
      /**
       * <code>string ownerUserId = 2;</code>
       * @param value The bytes for ownerUserId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOwnerUserIdBytes(value);
        return this;
      }

      /**
       * <code>string domain = 3;</code>
       * @return The domain.
       */
      @java.lang.Override
      public java.lang.String getDomain() {
        return instance.getDomain();
      }
      /**
       * <code>string domain = 3;</code>
       * @return The bytes for domain.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDomainBytes() {
        return instance.getDomainBytes();
      }
      /**
       * <code>string domain = 3;</code>
       * @param value The domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomain(
          java.lang.String value) {
        copyOnWrite();
        instance.setDomain(value);
        return this;
      }
      /**
       * <code>string domain = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDomain() {
        copyOnWrite();
        instance.clearDomain();
        return this;
      }
      /**
       * <code>string domain = 3;</code>
       * @param value The bytes for domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDomainBytes(value);
        return this;
      }

      /**
       * <code>.api.Deployment.Status status = 4;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.api.Deployment.Status status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.api.Deployment.Status status = 4;</code>
       * @return The status.
       */
      @java.lang.Override
      public api.DeploymentOuterClass.Deployment.Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.api.Deployment.Status status = 4;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(api.DeploymentOuterClass.Deployment.Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.api.Deployment.Status status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.Deployment)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.DeploymentOuterClass.Deployment();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "id_",
              "ownerUserId_",
              "domain_",
              "status_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.DeploymentOuterClass.Deployment> parser = PARSER;
          if (parser == null) {
            synchronized (api.DeploymentOuterClass.Deployment.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.DeploymentOuterClass.Deployment>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.Deployment)
    private static final api.DeploymentOuterClass.Deployment DEFAULT_INSTANCE;
    static {
      Deployment defaultInstance = new Deployment();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Deployment.class, defaultInstance);
    }

    public static api.DeploymentOuterClass.Deployment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Deployment> PARSER;

    public static com.google.protobuf.Parser<Deployment> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NewDeploymentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.NewDeployment)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string ownerUserId = 1;</code>
     * @return The ownerUserId.
     */
    java.lang.String getOwnerUserId();
    /**
     * <code>string ownerUserId = 1;</code>
     * @return The bytes for ownerUserId.
     */
    com.google.protobuf.ByteString
        getOwnerUserIdBytes();
  }
  /**
   * Protobuf type {@code api.NewDeployment}
   */
  public  static final class NewDeployment extends
      com.google.protobuf.GeneratedMessageLite<
          NewDeployment, NewDeployment.Builder> implements
      // @@protoc_insertion_point(message_implements:api.NewDeployment)
      NewDeploymentOrBuilder {
    private NewDeployment() {
      ownerUserId_ = "";
    }
    public static final int OWNERUSERID_FIELD_NUMBER = 1;
    private java.lang.String ownerUserId_;
    /**
     * <code>string ownerUserId = 1;</code>
     * @return The ownerUserId.
     */
    @java.lang.Override
    public java.lang.String getOwnerUserId() {
      return ownerUserId_;
    }
    /**
     * <code>string ownerUserId = 1;</code>
     * @return The bytes for ownerUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ownerUserId_);
    }
    /**
     * <code>string ownerUserId = 1;</code>
     * @param value The ownerUserId to set.
     */
    private void setOwnerUserId(
        java.lang.String value) {
      value.getClass();
  
      ownerUserId_ = value;
    }
    /**
     * <code>string ownerUserId = 1;</code>
     */
    private void clearOwnerUserId() {
      
      ownerUserId_ = getDefaultInstance().getOwnerUserId();
    }
    /**
     * <code>string ownerUserId = 1;</code>
     * @param value The bytes for ownerUserId to set.
     */
    private void setOwnerUserIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ownerUserId_ = value.toStringUtf8();
      
    }

    public static api.DeploymentOuterClass.NewDeployment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.NewDeployment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.NewDeployment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.NewDeployment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.NewDeployment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.NewDeployment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.NewDeployment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.NewDeployment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.DeploymentOuterClass.NewDeployment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.NewDeployment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.DeploymentOuterClass.NewDeployment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.NewDeployment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.DeploymentOuterClass.NewDeployment prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.NewDeployment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.DeploymentOuterClass.NewDeployment, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.NewDeployment)
        api.DeploymentOuterClass.NewDeploymentOrBuilder {
      // Construct using api.DeploymentOuterClass.NewDeployment.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string ownerUserId = 1;</code>
       * @return The ownerUserId.
       */
      @java.lang.Override
      public java.lang.String getOwnerUserId() {
        return instance.getOwnerUserId();
      }
      /**
       * <code>string ownerUserId = 1;</code>
       * @return The bytes for ownerUserId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOwnerUserIdBytes() {
        return instance.getOwnerUserIdBytes();
      }
      /**
       * <code>string ownerUserId = 1;</code>
       * @param value The ownerUserId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setOwnerUserId(value);
        return this;
      }
      /**
       * <code>string ownerUserId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerUserId() {
        copyOnWrite();
        instance.clearOwnerUserId();
        return this;
      }
      /**
       * <code>string ownerUserId = 1;</code>
       * @param value The bytes for ownerUserId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOwnerUserIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.NewDeployment)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.DeploymentOuterClass.NewDeployment();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "ownerUserId_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.DeploymentOuterClass.NewDeployment> parser = PARSER;
          if (parser == null) {
            synchronized (api.DeploymentOuterClass.NewDeployment.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.DeploymentOuterClass.NewDeployment>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.NewDeployment)
    private static final api.DeploymentOuterClass.NewDeployment DEFAULT_INSTANCE;
    static {
      NewDeployment defaultInstance = new NewDeployment();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NewDeployment.class, defaultInstance);
    }

    public static api.DeploymentOuterClass.NewDeployment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NewDeployment> PARSER;

    public static com.google.protobuf.Parser<NewDeployment> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetDeploymentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.GetDeploymentRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string ownerUserId = 1;</code>
     * @return The ownerUserId.
     */
    java.lang.String getOwnerUserId();
    /**
     * <code>string ownerUserId = 1;</code>
     * @return The bytes for ownerUserId.
     */
    com.google.protobuf.ByteString
        getOwnerUserIdBytes();

    /**
     * <code>string deploymentId = 2;</code>
     * @return The deploymentId.
     */
    java.lang.String getDeploymentId();
    /**
     * <code>string deploymentId = 2;</code>
     * @return The bytes for deploymentId.
     */
    com.google.protobuf.ByteString
        getDeploymentIdBytes();
  }
  /**
   * Protobuf type {@code api.GetDeploymentRequest}
   */
  public  static final class GetDeploymentRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetDeploymentRequest, GetDeploymentRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.GetDeploymentRequest)
      GetDeploymentRequestOrBuilder {
    private GetDeploymentRequest() {
      ownerUserId_ = "";
      deploymentId_ = "";
    }
    public static final int OWNERUSERID_FIELD_NUMBER = 1;
    private java.lang.String ownerUserId_;
    /**
     * <code>string ownerUserId = 1;</code>
     * @return The ownerUserId.
     */
    @java.lang.Override
    public java.lang.String getOwnerUserId() {
      return ownerUserId_;
    }
    /**
     * <code>string ownerUserId = 1;</code>
     * @return The bytes for ownerUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ownerUserId_);
    }
    /**
     * <code>string ownerUserId = 1;</code>
     * @param value The ownerUserId to set.
     */
    private void setOwnerUserId(
        java.lang.String value) {
      value.getClass();
  
      ownerUserId_ = value;
    }
    /**
     * <code>string ownerUserId = 1;</code>
     */
    private void clearOwnerUserId() {
      
      ownerUserId_ = getDefaultInstance().getOwnerUserId();
    }
    /**
     * <code>string ownerUserId = 1;</code>
     * @param value The bytes for ownerUserId to set.
     */
    private void setOwnerUserIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ownerUserId_ = value.toStringUtf8();
      
    }

    public static final int DEPLOYMENTID_FIELD_NUMBER = 2;
    private java.lang.String deploymentId_;
    /**
     * <code>string deploymentId = 2;</code>
     * @return The deploymentId.
     */
    @java.lang.Override
    public java.lang.String getDeploymentId() {
      return deploymentId_;
    }
    /**
     * <code>string deploymentId = 2;</code>
     * @return The bytes for deploymentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeploymentIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deploymentId_);
    }
    /**
     * <code>string deploymentId = 2;</code>
     * @param value The deploymentId to set.
     */
    private void setDeploymentId(
        java.lang.String value) {
      value.getClass();
  
      deploymentId_ = value;
    }
    /**
     * <code>string deploymentId = 2;</code>
     */
    private void clearDeploymentId() {
      
      deploymentId_ = getDefaultInstance().getDeploymentId();
    }
    /**
     * <code>string deploymentId = 2;</code>
     * @param value The bytes for deploymentId to set.
     */
    private void setDeploymentIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deploymentId_ = value.toStringUtf8();
      
    }

    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.GetDeploymentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.DeploymentOuterClass.GetDeploymentRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.GetDeploymentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.DeploymentOuterClass.GetDeploymentRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.GetDeploymentRequest)
        api.DeploymentOuterClass.GetDeploymentRequestOrBuilder {
      // Construct using api.DeploymentOuterClass.GetDeploymentRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string ownerUserId = 1;</code>
       * @return The ownerUserId.
       */
      @java.lang.Override
      public java.lang.String getOwnerUserId() {
        return instance.getOwnerUserId();
      }
      /**
       * <code>string ownerUserId = 1;</code>
       * @return The bytes for ownerUserId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOwnerUserIdBytes() {
        return instance.getOwnerUserIdBytes();
      }
      /**
       * <code>string ownerUserId = 1;</code>
       * @param value The ownerUserId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setOwnerUserId(value);
        return this;
      }
      /**
       * <code>string ownerUserId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerUserId() {
        copyOnWrite();
        instance.clearOwnerUserId();
        return this;
      }
      /**
       * <code>string ownerUserId = 1;</code>
       * @param value The bytes for ownerUserId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOwnerUserIdBytes(value);
        return this;
      }

      /**
       * <code>string deploymentId = 2;</code>
       * @return The deploymentId.
       */
      @java.lang.Override
      public java.lang.String getDeploymentId() {
        return instance.getDeploymentId();
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @return The bytes for deploymentId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeploymentIdBytes() {
        return instance.getDeploymentIdBytes();
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @param value The deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentId(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeploymentId(value);
        return this;
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeploymentId() {
        copyOnWrite();
        instance.clearDeploymentId();
        return this;
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @param value The bytes for deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeploymentIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.GetDeploymentRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.DeploymentOuterClass.GetDeploymentRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "ownerUserId_",
              "deploymentId_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.DeploymentOuterClass.GetDeploymentRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.DeploymentOuterClass.GetDeploymentRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.DeploymentOuterClass.GetDeploymentRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.GetDeploymentRequest)
    private static final api.DeploymentOuterClass.GetDeploymentRequest DEFAULT_INSTANCE;
    static {
      GetDeploymentRequest defaultInstance = new GetDeploymentRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetDeploymentRequest.class, defaultInstance);
    }

    public static api.DeploymentOuterClass.GetDeploymentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetDeploymentRequest> PARSER;

    public static com.google.protobuf.Parser<GetDeploymentRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RemoveDeploymentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.RemoveDeploymentRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string deploymentId = 1;</code>
     * @return The deploymentId.
     */
    java.lang.String getDeploymentId();
    /**
     * <code>string deploymentId = 1;</code>
     * @return The bytes for deploymentId.
     */
    com.google.protobuf.ByteString
        getDeploymentIdBytes();
  }
  /**
   * Protobuf type {@code api.RemoveDeploymentRequest}
   */
  public  static final class RemoveDeploymentRequest extends
      com.google.protobuf.GeneratedMessageLite<
          RemoveDeploymentRequest, RemoveDeploymentRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.RemoveDeploymentRequest)
      RemoveDeploymentRequestOrBuilder {
    private RemoveDeploymentRequest() {
      deploymentId_ = "";
    }
    public static final int DEPLOYMENTID_FIELD_NUMBER = 1;
    private java.lang.String deploymentId_;
    /**
     * <code>string deploymentId = 1;</code>
     * @return The deploymentId.
     */
    @java.lang.Override
    public java.lang.String getDeploymentId() {
      return deploymentId_;
    }
    /**
     * <code>string deploymentId = 1;</code>
     * @return The bytes for deploymentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeploymentIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deploymentId_);
    }
    /**
     * <code>string deploymentId = 1;</code>
     * @param value The deploymentId to set.
     */
    private void setDeploymentId(
        java.lang.String value) {
      value.getClass();
  
      deploymentId_ = value;
    }
    /**
     * <code>string deploymentId = 1;</code>
     */
    private void clearDeploymentId() {
      
      deploymentId_ = getDefaultInstance().getDeploymentId();
    }
    /**
     * <code>string deploymentId = 1;</code>
     * @param value The bytes for deploymentId to set.
     */
    private void setDeploymentIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deploymentId_ = value.toStringUtf8();
      
    }

    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.DeploymentOuterClass.RemoveDeploymentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.DeploymentOuterClass.RemoveDeploymentRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.RemoveDeploymentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.DeploymentOuterClass.RemoveDeploymentRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.RemoveDeploymentRequest)
        api.DeploymentOuterClass.RemoveDeploymentRequestOrBuilder {
      // Construct using api.DeploymentOuterClass.RemoveDeploymentRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string deploymentId = 1;</code>
       * @return The deploymentId.
       */
      @java.lang.Override
      public java.lang.String getDeploymentId() {
        return instance.getDeploymentId();
      }
      /**
       * <code>string deploymentId = 1;</code>
       * @return The bytes for deploymentId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeploymentIdBytes() {
        return instance.getDeploymentIdBytes();
      }
      /**
       * <code>string deploymentId = 1;</code>
       * @param value The deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentId(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeploymentId(value);
        return this;
      }
      /**
       * <code>string deploymentId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeploymentId() {
        copyOnWrite();
        instance.clearDeploymentId();
        return this;
      }
      /**
       * <code>string deploymentId = 1;</code>
       * @param value The bytes for deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeploymentIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.RemoveDeploymentRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.DeploymentOuterClass.RemoveDeploymentRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "deploymentId_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.DeploymentOuterClass.RemoveDeploymentRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.DeploymentOuterClass.RemoveDeploymentRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.DeploymentOuterClass.RemoveDeploymentRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.RemoveDeploymentRequest)
    private static final api.DeploymentOuterClass.RemoveDeploymentRequest DEFAULT_INSTANCE;
    static {
      RemoveDeploymentRequest defaultInstance = new RemoveDeploymentRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RemoveDeploymentRequest.class, defaultInstance);
    }

    public static api.DeploymentOuterClass.RemoveDeploymentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RemoveDeploymentRequest> PARSER;

    public static com.google.protobuf.Parser<RemoveDeploymentRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
