// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package api;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MeasurementEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.MeasurementEvent)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string peripheralId = 2;</code>
     * @return The peripheralId.
     */
    java.lang.String getPeripheralId();
    /**
     * <code>string peripheralId = 2;</code>
     * @return The bytes for peripheralId.
     */
    com.google.protobuf.ByteString
        getPeripheralIdBytes();

    /**
     * <code>string deploymentId = 3;</code>
     * @return The deploymentId.
     */
    java.lang.String getDeploymentId();
    /**
     * <code>string deploymentId = 3;</code>
     * @return The bytes for deploymentId.
     */
    com.google.protobuf.ByteString
        getDeploymentIdBytes();

    /**
     * <code>float value = 4;</code>
     * @return The value.
     */
    float getValue();

    /**
     * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
     * @return Whether the timeStamp field is set.
     */
    boolean hasTimeStamp();
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
     * @return The timeStamp.
     */
    com.google.protobuf.Timestamp getTimeStamp();
  }
  /**
   * Protobuf type {@code api.MeasurementEvent}
   */
  public  static final class MeasurementEvent extends
      com.google.protobuf.GeneratedMessageLite<
          MeasurementEvent, MeasurementEvent.Builder> implements
      // @@protoc_insertion_point(message_implements:api.MeasurementEvent)
      MeasurementEventOrBuilder {
    private MeasurementEvent() {
      id_ = "";
      peripheralId_ = "";
      deploymentId_ = "";
    }
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.String id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     */
    private void setId(
        java.lang.String value) {
      value.getClass();
  
      id_ = value;
    }
    /**
     * <code>string id = 1;</code>
     */
    private void clearId() {
      
      id_ = getDefaultInstance().getId();
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      id_ = value.toStringUtf8();
      
    }

    public static final int PERIPHERALID_FIELD_NUMBER = 2;
    private java.lang.String peripheralId_;
    /**
     * <code>string peripheralId = 2;</code>
     * @return The peripheralId.
     */
    @java.lang.Override
    public java.lang.String getPeripheralId() {
      return peripheralId_;
    }
    /**
     * <code>string peripheralId = 2;</code>
     * @return The bytes for peripheralId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeripheralIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(peripheralId_);
    }
    /**
     * <code>string peripheralId = 2;</code>
     * @param value The peripheralId to set.
     */
    private void setPeripheralId(
        java.lang.String value) {
      value.getClass();
  
      peripheralId_ = value;
    }
    /**
     * <code>string peripheralId = 2;</code>
     */
    private void clearPeripheralId() {
      
      peripheralId_ = getDefaultInstance().getPeripheralId();
    }
    /**
     * <code>string peripheralId = 2;</code>
     * @param value The bytes for peripheralId to set.
     */
    private void setPeripheralIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      peripheralId_ = value.toStringUtf8();
      
    }

    public static final int DEPLOYMENTID_FIELD_NUMBER = 3;
    private java.lang.String deploymentId_;
    /**
     * <code>string deploymentId = 3;</code>
     * @return The deploymentId.
     */
    @java.lang.Override
    public java.lang.String getDeploymentId() {
      return deploymentId_;
    }
    /**
     * <code>string deploymentId = 3;</code>
     * @return The bytes for deploymentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeploymentIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deploymentId_);
    }
    /**
     * <code>string deploymentId = 3;</code>
     * @param value The deploymentId to set.
     */
    private void setDeploymentId(
        java.lang.String value) {
      value.getClass();
  
      deploymentId_ = value;
    }
    /**
     * <code>string deploymentId = 3;</code>
     */
    private void clearDeploymentId() {
      
      deploymentId_ = getDefaultInstance().getDeploymentId();
    }
    /**
     * <code>string deploymentId = 3;</code>
     * @param value The bytes for deploymentId to set.
     */
    private void setDeploymentIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deploymentId_ = value.toStringUtf8();
      
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private float value_;
    /**
     * <code>float value = 4;</code>
     * @return The value.
     */
    @java.lang.Override
    public float getValue() {
      return value_;
    }
    /**
     * <code>float value = 4;</code>
     * @param value The value to set.
     */
    private void setValue(float value) {
      
      value_ = value;
    }
    /**
     * <code>float value = 4;</code>
     */
    private void clearValue() {
      
      value_ = 0F;
    }

    public static final int TIME_STAMP_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp timeStamp_;
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
     */
    @java.lang.Override
    public boolean hasTimeStamp() {
      return timeStamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimeStamp() {
      return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
     */
    private void setTimeStamp(com.google.protobuf.Timestamp value) {
      value.getClass();
  timeStamp_ = value;
      
      }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeTimeStamp(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (timeStamp_ != null &&
          timeStamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        timeStamp_ =
          com.google.protobuf.Timestamp.newBuilder(timeStamp_).mergeFrom(value).buildPartial();
      } else {
        timeStamp_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
     */
    private void clearTimeStamp() {  timeStamp_ = null;
      
    }

    public static api.Events.MeasurementEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.Events.MeasurementEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.Events.MeasurementEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.Events.MeasurementEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.Events.MeasurementEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.Events.MeasurementEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.Events.MeasurementEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.Events.MeasurementEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.Events.MeasurementEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static api.Events.MeasurementEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.Events.MeasurementEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.Events.MeasurementEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.Events.MeasurementEvent prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.MeasurementEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.Events.MeasurementEvent, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.MeasurementEvent)
        api.Events.MeasurementEventOrBuilder {
      // Construct using api.Events.MeasurementEvent.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <code>string peripheralId = 2;</code>
       * @return The peripheralId.
       */
      @java.lang.Override
      public java.lang.String getPeripheralId() {
        return instance.getPeripheralId();
      }
      /**
       * <code>string peripheralId = 2;</code>
       * @return The bytes for peripheralId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPeripheralIdBytes() {
        return instance.getPeripheralIdBytes();
      }
      /**
       * <code>string peripheralId = 2;</code>
       * @param value The peripheralId to set.
       * @return This builder for chaining.
       */
      public Builder setPeripheralId(
          java.lang.String value) {
        copyOnWrite();
        instance.setPeripheralId(value);
        return this;
      }
      /**
       * <code>string peripheralId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeripheralId() {
        copyOnWrite();
        instance.clearPeripheralId();
        return this;
      }
      /**
       * <code>string peripheralId = 2;</code>
       * @param value The bytes for peripheralId to set.
       * @return This builder for chaining.
       */
      public Builder setPeripheralIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPeripheralIdBytes(value);
        return this;
      }

      /**
       * <code>string deploymentId = 3;</code>
       * @return The deploymentId.
       */
      @java.lang.Override
      public java.lang.String getDeploymentId() {
        return instance.getDeploymentId();
      }
      /**
       * <code>string deploymentId = 3;</code>
       * @return The bytes for deploymentId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeploymentIdBytes() {
        return instance.getDeploymentIdBytes();
      }
      /**
       * <code>string deploymentId = 3;</code>
       * @param value The deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentId(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeploymentId(value);
        return this;
      }
      /**
       * <code>string deploymentId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeploymentId() {
        copyOnWrite();
        instance.clearDeploymentId();
        return this;
      }
      /**
       * <code>string deploymentId = 3;</code>
       * @param value The bytes for deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeploymentIdBytes(value);
        return this;
      }

      /**
       * <code>float value = 4;</code>
       * @return The value.
       */
      @java.lang.Override
      public float getValue() {
        return instance.getValue();
      }
      /**
       * <code>float value = 4;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(float value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>float value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
       */
      @java.lang.Override
      public boolean hasTimeStamp() {
        return instance.hasTimeStamp();
      }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getTimeStamp() {
        return instance.getTimeStamp();
      }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
       */
      public Builder setTimeStamp(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setTimeStamp(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
       */
      public Builder setTimeStamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setTimeStamp(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
       */
      public Builder mergeTimeStamp(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeTimeStamp(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 5;</code>
       */
      public Builder clearTimeStamp() {  copyOnWrite();
        instance.clearTimeStamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.MeasurementEvent)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.Events.MeasurementEvent();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "id_",
              "peripheralId_",
              "deploymentId_",
              "value_",
              "timeStamp_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0001\u0005\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.Events.MeasurementEvent> parser = PARSER;
          if (parser == null) {
            synchronized (api.Events.MeasurementEvent.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.Events.MeasurementEvent>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.MeasurementEvent)
    private static final api.Events.MeasurementEvent DEFAULT_INSTANCE;
    static {
      MeasurementEvent defaultInstance = new MeasurementEvent();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        MeasurementEvent.class, defaultInstance);
    }

    public static api.Events.MeasurementEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MeasurementEvent> PARSER;

    public static com.google.protobuf.Parser<MeasurementEvent> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NewMeasurementEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.NewMeasurementEvent)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string peripheralId = 1;</code>
     * @return The peripheralId.
     */
    java.lang.String getPeripheralId();
    /**
     * <code>string peripheralId = 1;</code>
     * @return The bytes for peripheralId.
     */
    com.google.protobuf.ByteString
        getPeripheralIdBytes();

    /**
     * <code>string deploymentId = 2;</code>
     * @return The deploymentId.
     */
    java.lang.String getDeploymentId();
    /**
     * <code>string deploymentId = 2;</code>
     * @return The bytes for deploymentId.
     */
    com.google.protobuf.ByteString
        getDeploymentIdBytes();

    /**
     * <code>float value = 3;</code>
     * @return The value.
     */
    float getValue();

    /**
     * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
     * @return Whether the timeStamp field is set.
     */
    boolean hasTimeStamp();
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
     * @return The timeStamp.
     */
    com.google.protobuf.Timestamp getTimeStamp();
  }
  /**
   * Protobuf type {@code api.NewMeasurementEvent}
   */
  public  static final class NewMeasurementEvent extends
      com.google.protobuf.GeneratedMessageLite<
          NewMeasurementEvent, NewMeasurementEvent.Builder> implements
      // @@protoc_insertion_point(message_implements:api.NewMeasurementEvent)
      NewMeasurementEventOrBuilder {
    private NewMeasurementEvent() {
      peripheralId_ = "";
      deploymentId_ = "";
    }
    public static final int PERIPHERALID_FIELD_NUMBER = 1;
    private java.lang.String peripheralId_;
    /**
     * <code>string peripheralId = 1;</code>
     * @return The peripheralId.
     */
    @java.lang.Override
    public java.lang.String getPeripheralId() {
      return peripheralId_;
    }
    /**
     * <code>string peripheralId = 1;</code>
     * @return The bytes for peripheralId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeripheralIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(peripheralId_);
    }
    /**
     * <code>string peripheralId = 1;</code>
     * @param value The peripheralId to set.
     */
    private void setPeripheralId(
        java.lang.String value) {
      value.getClass();
  
      peripheralId_ = value;
    }
    /**
     * <code>string peripheralId = 1;</code>
     */
    private void clearPeripheralId() {
      
      peripheralId_ = getDefaultInstance().getPeripheralId();
    }
    /**
     * <code>string peripheralId = 1;</code>
     * @param value The bytes for peripheralId to set.
     */
    private void setPeripheralIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      peripheralId_ = value.toStringUtf8();
      
    }

    public static final int DEPLOYMENTID_FIELD_NUMBER = 2;
    private java.lang.String deploymentId_;
    /**
     * <code>string deploymentId = 2;</code>
     * @return The deploymentId.
     */
    @java.lang.Override
    public java.lang.String getDeploymentId() {
      return deploymentId_;
    }
    /**
     * <code>string deploymentId = 2;</code>
     * @return The bytes for deploymentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeploymentIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deploymentId_);
    }
    /**
     * <code>string deploymentId = 2;</code>
     * @param value The deploymentId to set.
     */
    private void setDeploymentId(
        java.lang.String value) {
      value.getClass();
  
      deploymentId_ = value;
    }
    /**
     * <code>string deploymentId = 2;</code>
     */
    private void clearDeploymentId() {
      
      deploymentId_ = getDefaultInstance().getDeploymentId();
    }
    /**
     * <code>string deploymentId = 2;</code>
     * @param value The bytes for deploymentId to set.
     */
    private void setDeploymentIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deploymentId_ = value.toStringUtf8();
      
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private float value_;
    /**
     * <code>float value = 3;</code>
     * @return The value.
     */
    @java.lang.Override
    public float getValue() {
      return value_;
    }
    /**
     * <code>float value = 3;</code>
     * @param value The value to set.
     */
    private void setValue(float value) {
      
      value_ = value;
    }
    /**
     * <code>float value = 3;</code>
     */
    private void clearValue() {
      
      value_ = 0F;
    }

    public static final int TIME_STAMP_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp timeStamp_;
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
     */
    @java.lang.Override
    public boolean hasTimeStamp() {
      return timeStamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimeStamp() {
      return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
     */
    private void setTimeStamp(com.google.protobuf.Timestamp value) {
      value.getClass();
  timeStamp_ = value;
      
      }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeTimeStamp(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (timeStamp_ != null &&
          timeStamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        timeStamp_ =
          com.google.protobuf.Timestamp.newBuilder(timeStamp_).mergeFrom(value).buildPartial();
      } else {
        timeStamp_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
     */
    private void clearTimeStamp() {  timeStamp_ = null;
      
    }

    public static api.Events.NewMeasurementEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.Events.NewMeasurementEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.Events.NewMeasurementEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.Events.NewMeasurementEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.Events.NewMeasurementEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.Events.NewMeasurementEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.Events.NewMeasurementEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.Events.NewMeasurementEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.Events.NewMeasurementEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static api.Events.NewMeasurementEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.Events.NewMeasurementEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.Events.NewMeasurementEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.Events.NewMeasurementEvent prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.NewMeasurementEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.Events.NewMeasurementEvent, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.NewMeasurementEvent)
        api.Events.NewMeasurementEventOrBuilder {
      // Construct using api.Events.NewMeasurementEvent.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string peripheralId = 1;</code>
       * @return The peripheralId.
       */
      @java.lang.Override
      public java.lang.String getPeripheralId() {
        return instance.getPeripheralId();
      }
      /**
       * <code>string peripheralId = 1;</code>
       * @return The bytes for peripheralId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPeripheralIdBytes() {
        return instance.getPeripheralIdBytes();
      }
      /**
       * <code>string peripheralId = 1;</code>
       * @param value The peripheralId to set.
       * @return This builder for chaining.
       */
      public Builder setPeripheralId(
          java.lang.String value) {
        copyOnWrite();
        instance.setPeripheralId(value);
        return this;
      }
      /**
       * <code>string peripheralId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeripheralId() {
        copyOnWrite();
        instance.clearPeripheralId();
        return this;
      }
      /**
       * <code>string peripheralId = 1;</code>
       * @param value The bytes for peripheralId to set.
       * @return This builder for chaining.
       */
      public Builder setPeripheralIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPeripheralIdBytes(value);
        return this;
      }

      /**
       * <code>string deploymentId = 2;</code>
       * @return The deploymentId.
       */
      @java.lang.Override
      public java.lang.String getDeploymentId() {
        return instance.getDeploymentId();
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @return The bytes for deploymentId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeploymentIdBytes() {
        return instance.getDeploymentIdBytes();
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @param value The deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentId(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeploymentId(value);
        return this;
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeploymentId() {
        copyOnWrite();
        instance.clearDeploymentId();
        return this;
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @param value The bytes for deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeploymentIdBytes(value);
        return this;
      }

      /**
       * <code>float value = 3;</code>
       * @return The value.
       */
      @java.lang.Override
      public float getValue() {
        return instance.getValue();
      }
      /**
       * <code>float value = 3;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(float value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>float value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
       */
      @java.lang.Override
      public boolean hasTimeStamp() {
        return instance.hasTimeStamp();
      }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getTimeStamp() {
        return instance.getTimeStamp();
      }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
       */
      public Builder setTimeStamp(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setTimeStamp(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
       */
      public Builder setTimeStamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setTimeStamp(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
       */
      public Builder mergeTimeStamp(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeTimeStamp(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time_stamp = 4;</code>
       */
      public Builder clearTimeStamp() {  copyOnWrite();
        instance.clearTimeStamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.NewMeasurementEvent)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.Events.NewMeasurementEvent();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "peripheralId_",
              "deploymentId_",
              "value_",
              "timeStamp_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0001\u0004\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.Events.NewMeasurementEvent> parser = PARSER;
          if (parser == null) {
            synchronized (api.Events.NewMeasurementEvent.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.Events.NewMeasurementEvent>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.NewMeasurementEvent)
    private static final api.Events.NewMeasurementEvent DEFAULT_INSTANCE;
    static {
      NewMeasurementEvent defaultInstance = new NewMeasurementEvent();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NewMeasurementEvent.class, defaultInstance);
    }

    public static api.Events.NewMeasurementEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NewMeasurementEvent> PARSER;

    public static com.google.protobuf.Parser<NewMeasurementEvent> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MeasurementEventFilterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.MeasurementEventFilterRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string peripheralId = 1;</code>
     * @return The peripheralId.
     */
    java.lang.String getPeripheralId();
    /**
     * <code>string peripheralId = 1;</code>
     * @return The bytes for peripheralId.
     */
    com.google.protobuf.ByteString
        getPeripheralIdBytes();

    /**
     * <code>string deploymentId = 2;</code>
     * @return The deploymentId.
     */
    java.lang.String getDeploymentId();
    /**
     * <code>string deploymentId = 2;</code>
     * @return The bytes for deploymentId.
     */
    com.google.protobuf.ByteString
        getDeploymentIdBytes();

    /**
     * <code>.google.protobuf.Timestamp start_time = 3;</code>
     * @return Whether the startTime field is set.
     */
    boolean hasStartTime();
    /**
     * <code>.google.protobuf.Timestamp start_time = 3;</code>
     * @return The startTime.
     */
    com.google.protobuf.Timestamp getStartTime();

    /**
     * <code>.google.protobuf.Timestamp end_time = 4;</code>
     * @return Whether the endTime field is set.
     */
    boolean hasEndTime();
    /**
     * <code>.google.protobuf.Timestamp end_time = 4;</code>
     * @return The endTime.
     */
    com.google.protobuf.Timestamp getEndTime();
  }
  /**
   * Protobuf type {@code api.MeasurementEventFilterRequest}
   */
  public  static final class MeasurementEventFilterRequest extends
      com.google.protobuf.GeneratedMessageLite<
          MeasurementEventFilterRequest, MeasurementEventFilterRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.MeasurementEventFilterRequest)
      MeasurementEventFilterRequestOrBuilder {
    private MeasurementEventFilterRequest() {
      peripheralId_ = "";
      deploymentId_ = "";
    }
    public static final int PERIPHERALID_FIELD_NUMBER = 1;
    private java.lang.String peripheralId_;
    /**
     * <code>string peripheralId = 1;</code>
     * @return The peripheralId.
     */
    @java.lang.Override
    public java.lang.String getPeripheralId() {
      return peripheralId_;
    }
    /**
     * <code>string peripheralId = 1;</code>
     * @return The bytes for peripheralId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeripheralIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(peripheralId_);
    }
    /**
     * <code>string peripheralId = 1;</code>
     * @param value The peripheralId to set.
     */
    private void setPeripheralId(
        java.lang.String value) {
      value.getClass();
  
      peripheralId_ = value;
    }
    /**
     * <code>string peripheralId = 1;</code>
     */
    private void clearPeripheralId() {
      
      peripheralId_ = getDefaultInstance().getPeripheralId();
    }
    /**
     * <code>string peripheralId = 1;</code>
     * @param value The bytes for peripheralId to set.
     */
    private void setPeripheralIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      peripheralId_ = value.toStringUtf8();
      
    }

    public static final int DEPLOYMENTID_FIELD_NUMBER = 2;
    private java.lang.String deploymentId_;
    /**
     * <code>string deploymentId = 2;</code>
     * @return The deploymentId.
     */
    @java.lang.Override
    public java.lang.String getDeploymentId() {
      return deploymentId_;
    }
    /**
     * <code>string deploymentId = 2;</code>
     * @return The bytes for deploymentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeploymentIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deploymentId_);
    }
    /**
     * <code>string deploymentId = 2;</code>
     * @param value The deploymentId to set.
     */
    private void setDeploymentId(
        java.lang.String value) {
      value.getClass();
  
      deploymentId_ = value;
    }
    /**
     * <code>string deploymentId = 2;</code>
     */
    private void clearDeploymentId() {
      
      deploymentId_ = getDefaultInstance().getDeploymentId();
    }
    /**
     * <code>string deploymentId = 2;</code>
     * @param value The bytes for deploymentId to set.
     */
    private void setDeploymentIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deploymentId_ = value.toStringUtf8();
      
    }

    public static final int START_TIME_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp startTime_;
    /**
     * <code>.google.protobuf.Timestamp start_time = 3;</code>
     */
    @java.lang.Override
    public boolean hasStartTime() {
      return startTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getStartTime() {
      return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 3;</code>
     */
    private void setStartTime(com.google.protobuf.Timestamp value) {
      value.getClass();
  startTime_ = value;
      
      }
    /**
     * <code>.google.protobuf.Timestamp start_time = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeStartTime(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (startTime_ != null &&
          startTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        startTime_ =
          com.google.protobuf.Timestamp.newBuilder(startTime_).mergeFrom(value).buildPartial();
      } else {
        startTime_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 3;</code>
     */
    private void clearStartTime() {  startTime_ = null;
      
    }

    public static final int END_TIME_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp endTime_;
    /**
     * <code>.google.protobuf.Timestamp end_time = 4;</code>
     */
    @java.lang.Override
    public boolean hasEndTime() {
      return endTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getEndTime() {
      return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 4;</code>
     */
    private void setEndTime(com.google.protobuf.Timestamp value) {
      value.getClass();
  endTime_ = value;
      
      }
    /**
     * <code>.google.protobuf.Timestamp end_time = 4;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeEndTime(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (endTime_ != null &&
          endTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        endTime_ =
          com.google.protobuf.Timestamp.newBuilder(endTime_).mergeFrom(value).buildPartial();
      } else {
        endTime_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 4;</code>
     */
    private void clearEndTime() {  endTime_ = null;
      
    }

    public static api.Events.MeasurementEventFilterRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.Events.MeasurementEventFilterRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.Events.MeasurementEventFilterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.Events.MeasurementEventFilterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.Events.MeasurementEventFilterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.Events.MeasurementEventFilterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.Events.MeasurementEventFilterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.Events.MeasurementEventFilterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.Events.MeasurementEventFilterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static api.Events.MeasurementEventFilterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.Events.MeasurementEventFilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.Events.MeasurementEventFilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.Events.MeasurementEventFilterRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.MeasurementEventFilterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.Events.MeasurementEventFilterRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.MeasurementEventFilterRequest)
        api.Events.MeasurementEventFilterRequestOrBuilder {
      // Construct using api.Events.MeasurementEventFilterRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string peripheralId = 1;</code>
       * @return The peripheralId.
       */
      @java.lang.Override
      public java.lang.String getPeripheralId() {
        return instance.getPeripheralId();
      }
      /**
       * <code>string peripheralId = 1;</code>
       * @return The bytes for peripheralId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPeripheralIdBytes() {
        return instance.getPeripheralIdBytes();
      }
      /**
       * <code>string peripheralId = 1;</code>
       * @param value The peripheralId to set.
       * @return This builder for chaining.
       */
      public Builder setPeripheralId(
          java.lang.String value) {
        copyOnWrite();
        instance.setPeripheralId(value);
        return this;
      }
      /**
       * <code>string peripheralId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeripheralId() {
        copyOnWrite();
        instance.clearPeripheralId();
        return this;
      }
      /**
       * <code>string peripheralId = 1;</code>
       * @param value The bytes for peripheralId to set.
       * @return This builder for chaining.
       */
      public Builder setPeripheralIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPeripheralIdBytes(value);
        return this;
      }

      /**
       * <code>string deploymentId = 2;</code>
       * @return The deploymentId.
       */
      @java.lang.Override
      public java.lang.String getDeploymentId() {
        return instance.getDeploymentId();
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @return The bytes for deploymentId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeploymentIdBytes() {
        return instance.getDeploymentIdBytes();
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @param value The deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentId(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeploymentId(value);
        return this;
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeploymentId() {
        copyOnWrite();
        instance.clearDeploymentId();
        return this;
      }
      /**
       * <code>string deploymentId = 2;</code>
       * @param value The bytes for deploymentId to set.
       * @return This builder for chaining.
       */
      public Builder setDeploymentIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeploymentIdBytes(value);
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp start_time = 3;</code>
       */
      @java.lang.Override
      public boolean hasStartTime() {
        return instance.hasStartTime();
      }
      /**
       * <code>.google.protobuf.Timestamp start_time = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getStartTime() {
        return instance.getStartTime();
      }
      /**
       * <code>.google.protobuf.Timestamp start_time = 3;</code>
       */
      public Builder setStartTime(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setStartTime(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp start_time = 3;</code>
       */
      public Builder setStartTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setStartTime(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp start_time = 3;</code>
       */
      public Builder mergeStartTime(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeStartTime(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp start_time = 3;</code>
       */
      public Builder clearStartTime() {  copyOnWrite();
        instance.clearStartTime();
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp end_time = 4;</code>
       */
      @java.lang.Override
      public boolean hasEndTime() {
        return instance.hasEndTime();
      }
      /**
       * <code>.google.protobuf.Timestamp end_time = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getEndTime() {
        return instance.getEndTime();
      }
      /**
       * <code>.google.protobuf.Timestamp end_time = 4;</code>
       */
      public Builder setEndTime(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setEndTime(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp end_time = 4;</code>
       */
      public Builder setEndTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setEndTime(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp end_time = 4;</code>
       */
      public Builder mergeEndTime(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeEndTime(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp end_time = 4;</code>
       */
      public Builder clearEndTime() {  copyOnWrite();
        instance.clearEndTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.MeasurementEventFilterRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.Events.MeasurementEventFilterRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "peripheralId_",
              "deploymentId_",
              "startTime_",
              "endTime_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\t\u0004\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.Events.MeasurementEventFilterRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.Events.MeasurementEventFilterRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.Events.MeasurementEventFilterRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.MeasurementEventFilterRequest)
    private static final api.Events.MeasurementEventFilterRequest DEFAULT_INSTANCE;
    static {
      MeasurementEventFilterRequest defaultInstance = new MeasurementEventFilterRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        MeasurementEventFilterRequest.class, defaultInstance);
    }

    public static api.Events.MeasurementEventFilterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MeasurementEventFilterRequest> PARSER;

    public static com.google.protobuf.Parser<MeasurementEventFilterRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
