# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: deployment.endpoints.microclimates-299418.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Deployment Management Service API
apis:
- name: api.DeploymentManagementService

#
# API usage restrictions.
#
usage:
  rules:
  # get all deployments that belong to a user
  - selector: api.DeploymentManagementService.GetDeploymentsForUser
    allow_unregistered_calls: true
  # create a deployment for a user
  - selector: api.DeploymentManagementService.CreateDeployment
    allow_unregistered_calls: true
  # get a deployment
  - selector: api.DeploymentManagementService.GetDeployment
    allow_unregistered_calls: true
  # remove a deployment
  - selector: api.DeploymentManagementService.RemoveDeployment
    allow_unregistered_calls: true

authentication:
  providers:
  - id: google_service_account
    issuer: microclimates-consumer@microclimates-consumer.iam.gserviceaccount.com
    jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/microclimates-consumer@microclimates-consumer.iam.gserviceaccount.com
  - id: firebase
    jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
    audiences: microclimates-client
    issuer: https://securetoken.google.com/microclimates-client
    jwt_locations:
    - header: "jwt-header-foo"
      value_prefix: "jwt-prefix-foo"
    - query: "jwt_query_bar"
  rules:
  - selector: "*"
    requirements:
      - provider_id: firebase
      - provider_id: google_service_account
