// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: peripheral.proto

package peripheral

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	apipb "protobuf/api/apipb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Peripheral_PeripheralType int32

const (
	Peripheral_THERMAL  Peripheral_PeripheralType = 0
	Peripheral_PARTICLE Peripheral_PeripheralType = 1
)

// Enum value maps for Peripheral_PeripheralType.
var (
	Peripheral_PeripheralType_name = map[int32]string{
		0: "THERMAL",
		1: "PARTICLE",
	}
	Peripheral_PeripheralType_value = map[string]int32{
		"THERMAL":  0,
		"PARTICLE": 1,
	}
)

func (x Peripheral_PeripheralType) Enum() *Peripheral_PeripheralType {
	p := new(Peripheral_PeripheralType)
	*p = x
	return p
}

func (x Peripheral_PeripheralType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Peripheral_PeripheralType) Descriptor() protoreflect.EnumDescriptor {
	return file_peripheral_proto_enumTypes[0].Descriptor()
}

func (Peripheral_PeripheralType) Type() protoreflect.EnumType {
	return &file_peripheral_proto_enumTypes[0]
}

func (x Peripheral_PeripheralType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Peripheral_PeripheralType.Descriptor instead.
func (Peripheral_PeripheralType) EnumDescriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{0, 0}
}

type Peripheral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int32                     `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DeploymentId int32                     `protobuf:"varint,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	PeripheralId int32                     `protobuf:"varint,3,opt,name=peripheralId,proto3" json:"peripheralId,omitempty"`
	Type         Peripheral_PeripheralType `protobuf:"varint,4,opt,name=type,proto3,enum=api.Peripheral_PeripheralType" json:"type,omitempty"`
}

func (x *Peripheral) Reset() {
	*x = Peripheral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peripheral_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peripheral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peripheral) ProtoMessage() {}

func (x *Peripheral) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peripheral.ProtoReflect.Descriptor instead.
func (*Peripheral) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{0}
}

func (x *Peripheral) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Peripheral) GetDeploymentId() int32 {
	if x != nil {
		return x.DeploymentId
	}
	return 0
}

func (x *Peripheral) GetPeripheralId() int32 {
	if x != nil {
		return x.PeripheralId
	}
	return 0
}

func (x *Peripheral) GetType() Peripheral_PeripheralType {
	if x != nil {
		return x.Type
	}
	return Peripheral_THERMAL
}

var File_peripheral_proto protoreflect.FileDescriptor

var file_peripheral_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x0b, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61,
	0x6c, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72,
	0x61, 0x6c, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x69, 0x70,
	0x68, 0x65, 0x72, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x48, 0x45,
	0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x41, 0x52, 0x54, 0x49, 0x43,
	0x4c, 0x45, 0x10, 0x01, 0x32, 0x84, 0x01, 0x0a, 0x1b, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x61, 0x6c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65,
	0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x2f, 0x0a, 0x10, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x0f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x1a,
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x15, 0x5a, 0x13, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72,
	0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_peripheral_proto_rawDescOnce sync.Once
	file_peripheral_proto_rawDescData = file_peripheral_proto_rawDesc
)

func file_peripheral_proto_rawDescGZIP() []byte {
	file_peripheral_proto_rawDescOnce.Do(func() {
		file_peripheral_proto_rawDescData = protoimpl.X.CompressGZIP(file_peripheral_proto_rawDescData)
	})
	return file_peripheral_proto_rawDescData
}

var file_peripheral_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peripheral_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_peripheral_proto_goTypes = []interface{}{
	(Peripheral_PeripheralType)(0), // 0: api.Peripheral.PeripheralType
	(*Peripheral)(nil),             // 1: api.Peripheral
	(*apipb.Empty)(nil),            // 2: api.Empty
}
var file_peripheral_proto_depIdxs = []int32{
	0, // 0: api.Peripheral.type:type_name -> api.Peripheral.PeripheralType
	1, // 1: api.PeripheralManagementService.CreatePeripheral:input_type -> api.Peripheral
	1, // 2: api.PeripheralManagementService.RemovePeripheral:input_type -> api.Peripheral
	1, // 3: api.PeripheralManagementService.CreatePeripheral:output_type -> api.Peripheral
	2, // 4: api.PeripheralManagementService.RemovePeripheral:output_type -> api.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_peripheral_proto_init() }
func file_peripheral_proto_init() {
	if File_peripheral_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_peripheral_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peripheral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peripheral_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peripheral_proto_goTypes,
		DependencyIndexes: file_peripheral_proto_depIdxs,
		EnumInfos:         file_peripheral_proto_enumTypes,
		MessageInfos:      file_peripheral_proto_msgTypes,
	}.Build()
	File_peripheral_proto = out.File
	file_peripheral_proto_rawDesc = nil
	file_peripheral_proto_goTypes = nil
	file_peripheral_proto_depIdxs = nil
}
